BaseUrl = "http://grandesdados.com/"
LanguageCode = "pt-br"
Title = "Grandes Dados"
Copyright = "Todos os direitos reservados - 2015"
CanonifyUrls = true
Theme = "casper"

DisqusShortname = "grandesdados"

[params]
  description = "Blog de BigData"
  cover = "images/cover.jpg"
  googleAnalyticsUserID = "UA-38960920-6"
  githubName = "GrandesDados"
  hideHUGOSupport = false

[[menu.main]]
  name = "Blog"
  weight = -120
  identifier = "blog"
  url = "/"

[[menu.main]]
  name = "GitHub"
  weight = 100
  url = "https://github.com/GrandesDados"
